services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: backend_app
    expose:
      - "5000"
    volumes:
      - .:/app

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped